### ISSUE TITLE
Site branding in mobile needs improvement

### ISSUE THREAD

**Issue by imath** [WordCampParis/2019#1]
Move the following rule into the min width media query

```css
body:not(.title-tagline-hidden) .site-branding {
	display: inline-block;
	vertical-align: middle;
}
```
